using System.Collections.Generic;
using Hartsy.Extensions.APIBackends.Models;

namespace Hartsy.Extensions.APIBackends.Providers;

/// <summary>Static definitions for all API providers using the type-safe factory pattern.</summary>
public static class ProviderDefinitions
{
    /// <summary>Gets all provider definitions.</summary>
    public static IReadOnlyList<ProviderDefinition> All => [OpenAI, Ideogram, BlackForestLabs, Grok, Google, Fal];

    #region OpenAI Provider

    public static ProviderDefinition OpenAI => ProviderDefinitionBuilder.Create()
        .WithId("openai_api")
        .WithName("OpenAI")
        .WithModelPrefix("OpenAI")
        .WithBaseUrl("https://api.openai.com/v1/images/generations")
        .WithAuthHeader("Bearer")
        .WithModelClass("openai_api", "DALL-E")
        .AddModels(OpenAIModels)
        .Build();

    private static IEnumerable<ModelDefinition> OpenAIModels =>
    [
        ModelDefinitionBuilder.Create()
            .WithId("dall-e-2")
            .WithTitle("DALL-E 2")
            .WithDescription("OpenAI's DALL-E 2 model for image generation")
            .WithAuthor("OpenAI")
            .WithDimensions(1024, 1024)
            .WithPreviewImage("Images/ModelPreviews/dalle2.png")
            .WithDate("2022")
            .WithUsageHint("Good for general image generation via API")
            .WithTags("dall-e", "generative")
            .WithFeatureFlag("dalle2_params")
            .Build(),

        ModelDefinitionBuilder.Create()
            .WithId("dall-e-3")
            .WithTitle("DALL-E 3")
            .WithDescription("Advanced generative model for creating highly detailed and accurate images")
            .WithAuthor("OpenAI")
            .WithDimensions(1024, 1024)
            .WithPreviewImage("Images/ModelPreviews/dalle.png")
            .WithDate("2023")
            .WithUsageHint("Excellent for high-quality image generation with accurate text representation")
            .WithTags("dall-e", "high-quality", "text-accurate")
            .WithFeatureFlag("dalle3_params")
            .Build(),

        ModelDefinitionBuilder.Create()
            .WithId("gpt-image-1")
            .WithTitle("GPT Image 1")
            .WithDescription("Generates images with strong instruction following, contextual awareness, and world knowledge")
            .WithAuthor("OpenAI")
            .WithDimensions(1024, 1024)
            .WithPreviewImage("Images/ModelPreviews/gpt-image-1.png")
            .WithDate("2025")
            .WithUsageHint("Best for context-aware image generation and edits")
            .WithTags("gpt-image", "high-quality", "text-accurate")
            .WithFeatureFlag("gpt-image-1_params")
            .Build(),

        ModelDefinitionBuilder.Create()
            .WithId("gpt-image-1.5")
            .WithTitle("GPT Image 1.5")
            .WithDescription("High-fidelity images with strong instruction following and accurate visual details")
            .WithAuthor("OpenAI")
            .WithDimensions(1024, 1024)
            .WithPreviewImage("Images/ModelPreviews/gpt-image-1.5.png")
            .WithDate("2025")
            .WithUsageHint("Best for context-aware image generation requiring strong instruction following")
            .WithTags("gpt-image", "high-quality", "text-accurate")
            .WithFeatureFlag("gpt-image-1.5_params")
            .Build()
    ];

    #endregion

    #region Ideogram Provider

    public static ProviderDefinition Ideogram => ProviderDefinitionBuilder.Create()
        .WithId("ideogram_api")
        .WithName("Ideogram")
        .WithModelPrefix("Ideogram")
        .WithBaseUrl("https://api.ideogram.ai/generate")
        .WithAuthHeader("Bearer", "Api-Key")
        .WithModelClass("ideogram_api", "Ideogram")
        .AddModels(IdeogramModels)
        .Build();

    private static IEnumerable<ModelDefinition> IdeogramModels =>
    [
        ModelDefinitionBuilder.Create()
            .WithId("V_1")
            .WithTitle("Ideogram V1")
            .WithDescription("First generation Ideogram model with strong text rendering")
            .WithAuthor("Ideogram")
            .WithDimensions(1024, 1024)
            .WithPreviewImage("Images/ModelPreviews/ideogram_v1.png")
            .WithDate("2023")
            .WithUsageHint("Good for images requiring accurate text rendering")
            .WithTags("text-rendering", "generative")
            .WithFeatureFlag("ideogram_v1_params")
            .Build(),

        ModelDefinitionBuilder.Create()
            .WithId("V_2")
            .WithTitle("Ideogram V2")
            .WithDescription("Second generation with improved quality and text accuracy")
            .WithAuthor("Ideogram")
            .WithDimensions(1024, 1024)
            .WithPreviewImage("Images/ModelPreviews/ideogram_v2.png")
            .WithDate("2024")
            .WithUsageHint("Enhanced text rendering and image quality")
            .WithTags("text-rendering", "high-quality")
            .WithFeatureFlag("ideogram_v2_params")
            .Build(),

        ModelDefinitionBuilder.Create()
            .WithId("V_2_TURBO")
            .WithTitle("Ideogram V2 Turbo")
            .WithDescription("Faster V2 generation with optimized performance")
            .WithAuthor("Ideogram")
            .WithDimensions(1024, 1024)
            .WithPreviewImage("Images/ModelPreviews/ideogram_v2_turbo.png")
            .WithDate("2024")
            .WithUsageHint("Fast generation with good quality")
            .WithTags("text-rendering", "fast")
            .WithFeatureFlag("ideogram_v2_params")
            .Build(),

        ModelDefinitionBuilder.Create()
            .WithId("V_3")
            .WithTitle("Ideogram V3")
            .WithDescription("Latest generation with best-in-class text rendering and image quality")
            .WithAuthor("Ideogram")
            .WithDimensions(1024, 1024)
            .WithPreviewImage("Images/ModelPreviews/ideogram_v3.png")
            .WithDate("2025")
            .WithUsageHint("Best for professional-grade images with perfect text")
            .WithTags("text-rendering", "premium", "high-quality")
            .WithFeatureFlag("ideogram_v3_params")
            .Build()
    ];

    #endregion

    #region Black Forest Labs Provider

    public static ProviderDefinition BlackForestLabs => ProviderDefinitionBuilder.Create()
        .WithId("bfl_api")
        .WithName("Black Forest Labs")
        .WithModelPrefix("BFL")
        .WithBaseUrl("https://api.bfl.ai")
        .WithAuthHeader("Bearer", "x-key")
        .WithModelClass("bfl_api", "FLUX")
        .AddModels(BlackForestModels)
        .Build();

    private static IEnumerable<ModelDefinition> BlackForestModels =>
    [
        ModelDefinitionBuilder.Create()
            .WithId("flux-pro-1.1")
            .WithTitle("FLUX Pro 1.1")
            .WithDescription("Professional-grade FLUX model with enhanced capabilities")
            .WithAuthor("Black Forest Labs")
            .WithDimensions(1024, 1024)
            .WithPreviewImage("Images/ModelPreviews/flux-pro.png")
            .WithDate("2024")
            .WithUsageHint("High-quality professional image generation")
            .WithTags("flux", "professional", "high-quality")
            .WithFeatureFlag("flux_pro_params")
            .Build(),

        ModelDefinitionBuilder.Create()
            .WithId("flux-pro-1.1-ultra")
            .WithTitle("FLUX Pro 1.1 Ultra")
            .WithDescription("Ultra high-resolution FLUX model up to 2K with improved realism")
            .WithAuthor("Black Forest Labs")
            .WithDimensions(2048, 2048)
            .WithPreviewImage("Images/ModelPreviews/flux-ultra.png")
            .WithDate("2024")
            .WithUsageHint("Best for ultra high-resolution professional images")
            .WithTags("flux", "ultra", "2k", "realism")
            .WithFeatureFlag("flux_ultra_params")
            .Build(),

        ModelDefinitionBuilder.Create()
            .WithId("flux-dev")
            .WithTitle("FLUX Dev")
            .WithDescription("Development version of FLUX for experimentation")
            .WithAuthor("Black Forest Labs")
            .WithDimensions(1024, 1024)
            .WithPreviewImage("Images/ModelPreviews/flux-dev.png")
            .WithDate("2024")
            .WithUsageHint("Good for testing and development")
            .WithTags("flux", "dev")
            .WithFeatureFlag("flux_dev_params")
            .Build(),

        ModelDefinitionBuilder.Create()
            .WithId("flux-kontext-pro")
            .WithTitle("FLUX Kontext Pro")
            .WithDescription("Context-aware FLUX model for targeted edits and transformations")
            .WithAuthor("Black Forest Labs")
            .WithDimensions(1024, 1024)
            .WithPreviewImage("Images/ModelPreviews/flux-kontext.png")
            .WithDate("2024")
            .WithUsageHint("Best for image editing and context-aware generation")
            .WithTags("flux", "kontext", "editing")
            .WithFeatureFlag("flux_kontext_pro_params")
            .Build(),

        ModelDefinitionBuilder.Create()
            .WithId("flux-kontext-max")
            .WithTitle("FLUX Kontext Max")
            .WithDescription("Maximum capability context-aware FLUX model")
            .WithAuthor("Black Forest Labs")
            .WithDimensions(1024, 1024)
            .WithPreviewImage("Images/ModelPreviews/flux-kontext-max.png")
            .WithDate("2024")
            .WithUsageHint("Premium context-aware generation and editing")
            .WithTags("flux", "kontext", "premium")
            .WithFeatureFlag("flux_kontext_max_params")
            .Build(),

        ModelDefinitionBuilder.Create()
            .WithId("flux-2-pro")
            .WithTitle("FLUX 2 Pro")
            .WithDescription("Second generation professional FLUX model")
            .WithAuthor("Black Forest Labs")
            .WithDimensions(1024, 1024)
            .WithPreviewImage("Images/ModelPreviews/flux-2-pro.png")
            .WithDate("2025")
            .WithUsageHint("Latest professional-grade FLUX generation")
            .WithTags("flux", "flux2", "professional")
            .WithFeatureFlag("flux_2_pro_params")
            .Build(),

        ModelDefinitionBuilder.Create()
            .WithId("flux-2-max")
            .WithTitle("FLUX 2 Max")
            .WithDescription("Maximum capability second generation FLUX model")
            .WithAuthor("Black Forest Labs")
            .WithDimensions(1024, 1024)
            .WithPreviewImage("Images/ModelPreviews/flux-2-max.png")
            .WithDate("2025")
            .WithUsageHint("Premium FLUX 2 generation with maximum quality")
            .WithTags("flux", "flux2", "premium")
            .WithFeatureFlag("flux_2_max_params")
            .Build()
    ];

    #endregion

    #region Grok Provider

    public static ProviderDefinition Grok => ProviderDefinitionBuilder.Create()
        .WithId("grok_api")
        .WithName("Grok")
        .WithModelPrefix("Grok")
        .WithBaseUrl("https://api.x.ai/v1/images/generations")
        .WithAuthHeader("Bearer")
        .WithModelClass("grok_api", "Grok")
        .AddModels(GrokModels)
        .Build();

    private static IEnumerable<ModelDefinition> GrokModels =>
    [
        ModelDefinitionBuilder.Create()
            .WithId("grok-2-image")
            .WithTitle("Grok 2 Image")
            .WithDescription("xAI's Grok 2 image generation model")
            .WithAuthor("xAI")
            .WithDimensions(1024, 1024)
            .WithPreviewImage("Images/ModelPreviews/grok.png")
            .WithDate("2024")
            .WithUsageHint("High-quality image generation from xAI")
            .WithTags("grok", "xai", "generative")
            .WithFeatureFlag("grok_2_image_params")
            .Build()
    ];

    #endregion

    #region Google Provider

    public static ProviderDefinition Google => ProviderDefinitionBuilder.Create()
        .WithId("google_api")
        .WithName("Google")
        .WithModelPrefix("Google")
        .WithBaseUrl("https://generativelanguage.googleapis.com/v1beta/models")
        .WithAuthHeader("Bearer")
        .WithModelClass("google_api", "Google Imagen")
        .AddModels(GoogleModels)
        .Build();

    private static IEnumerable<ModelDefinition> GoogleModels =>
    [
        ModelDefinitionBuilder.Create()
            .WithId("imagen-3.0-generate-002")
            .WithTitle("Imagen 3.0")
            .WithDescription("Google's Imagen 3.0 image generation model")
            .WithAuthor("Google")
            .WithDimensions(1024, 1024)
            .WithPreviewImage("Images/ModelPreviews/imagen.png")
            .WithDate("2024")
            .WithUsageHint("High-quality image generation from Google")
            .WithTags("imagen", "google", "generative")
            .WithFeatureFlag("google_imagen_params")
            .Build(),

        ModelDefinitionBuilder.Create()
            .WithId("gemini-2.0-flash-preview-image-generation")
            .WithTitle("Gemini 2.0 Flash Image")
            .WithDescription("Gemini 2.0 Flash with image generation capabilities")
            .WithAuthor("Google")
            .WithDimensions(1024, 1024)
            .WithPreviewImage("Images/ModelPreviews/gemini.png")
            .WithDate("2024")
            .WithUsageHint("Fast multimodal image generation")
            .WithTags("gemini", "google", "multimodal")
            .WithFeatureFlag("google_gemini_params")
            .Build()
    ];

    #endregion

    #region Fal.ai Provider

    public static ProviderDefinition Fal => ProviderDefinitionBuilder.Create()
        .WithId("fal_api")
        .WithName("Fal.ai")
        .WithModelPrefix("Fal")
        .WithBaseUrl("https://fal.run")
        .WithAuthHeader("Key", "Authorization")
        .WithModelClass("fal_api", "Fal.ai")
        .AddModels(FalModels)
        .Build();

    private static IEnumerable<ModelDefinition> FalModels =>
    [
        // ==================== FLUX (Black Forest Labs) ====================
        ModelDefinitionBuilder.Create()
            .WithId("FLUX/flux-dev")
            .WithEndpointOverride("fal-ai/flux/dev")
            .WithTitle("FLUX.1 [dev]")
            .WithDescription("12B parameter flow transformer for high-quality text-to-image generation")
            .WithAuthor("Black Forest Labs")
            .WithDimensions(1024, 1024)
            .WithDate("2024")
            .WithUsageHint("High-quality text-to-image with 28 inference steps")
            .WithTags("flux", "text-to-image", "high-quality")
            .WithFeatureFlag("fal_t2i_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("FLUX/flux-schnell")
            .WithEndpointOverride("fal-ai/flux/schnell")
            .WithTitle("FLUX.1 [schnell]")
            .WithDescription("Fast FLUX model generating high-quality images in 1-4 steps")
            .WithAuthor("Black Forest Labs")
            .WithDimensions(1024, 1024)
            .WithDate("2024")
            .WithUsageHint("Ultra-fast generation, great for rapid iteration")
            .WithTags("flux", "text-to-image", "fast")
            .WithFeatureFlag("fal_t2i_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("FLUX/flux-pro-ultra")
            .WithEndpointOverride("fal-ai/flux-pro/v1.1-ultra")
            .WithTitle("FLUX 1.1 [pro] ultra")
            .WithDescription("Professional FLUX with up to 2K resolution and improved photo realism")
            .WithAuthor("Black Forest Labs")
            .WithDimensions(2048, 2048)
            .WithDate("2024")
            .WithUsageHint("Best for high-resolution professional images")
            .WithTags("flux", "text-to-image", "2k", "realism", "professional")
            .WithFeatureFlag("fal_t2i_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("FLUX/flux-kontext-pro")
            .WithEndpointOverride("fal-ai/flux-pro/kontext")
            .WithTitle("FLUX.1 Kontext [pro]")
            .WithDescription("Context-aware FLUX for targeted edits and complex scene transformations")
            .WithAuthor("Black Forest Labs")
            .WithDimensions(1024, 1024)
            .WithDate("2024")
            .WithUsageHint("Best for image editing with text and reference images")
            .WithTags("flux", "image-to-image", "editing", "kontext")
            .WithFeatureFlag("fal_t2i_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("FLUX/flux-kontext-max")
            .WithEndpointOverride("fal-ai/flux-pro/kontext/max")
            .WithTitle("FLUX Kontext [max]")
            .WithDescription("Maximum capability context-aware editing model")
            .WithAuthor("Black Forest Labs")
            .WithDimensions(1024, 1024)
            .WithDate("2024")
            .WithUsageHint("Premium image editing with maximum quality")
            .WithTags("flux", "image-to-image", "editing", "kontext", "premium")
            .WithFeatureFlag("fal_t2i_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("FLUX/flux-2-flex")
            .WithEndpointOverride("fal-ai/flux-2-flex")
            .WithTitle("FLUX.2 [flex]")
            .WithDescription("FLUX.2 with adjustable inference steps, guidance scale, and enhanced typography")
            .WithAuthor("Black Forest Labs")
            .WithDimensions(1024, 1024)
            .WithDate("2025")
            .WithUsageHint("Fine-tuned control with excellent text rendering")
            .WithTags("flux", "text-to-image", "typography", "flux2")
            .WithFeatureFlag("fal_t2i_params")
            .Build(),

        // ==================== Recraft ====================
        ModelDefinitionBuilder.Create()
            .WithId("Recraft/recraft-v3")
            .WithEndpointOverride("fal-ai/recraft/v3/text-to-image")
            .WithTitle("Recraft V3")
            .WithDescription("SOTA text-to-image with long text generation, vector art, and brand style support")
            .WithAuthor("Recraft")
            .WithDimensions(1024, 1024)
            .WithDate("2024")
            .WithUsageHint("Best for vector art, typography, and brand-consistent images")
            .WithTags("recraft", "text-to-image", "vector", "typography", "style")
            .WithFeatureFlag("fal_t2i_params")
            .Build(),

        // ==================== Ideogram ====================
        ModelDefinitionBuilder.Create()
            .WithId("Ideogram/ideogram-v2-turbo")
            .WithEndpointOverride("fal-ai/ideogram/v2/turbo")
            .WithTitle("Ideogram V2 Turbo")
            .WithDescription("Fast Ideogram V2 with excellent text rendering via Fal.ai")
            .WithAuthor("Ideogram")
            .WithDimensions(1024, 1024)
            .WithDate("2024")
            .WithUsageHint("Fast generation with superior text rendering")
            .WithTags("ideogram", "text-to-image", "text-rendering", "fast")
            .WithFeatureFlag("fal_t2i_params")
            .Build(),

        // ==================== Stability AI ====================
        ModelDefinitionBuilder.Create()
            .WithId("StabilityAI/sd-v35-large")
            .WithEndpointOverride("fal-ai/stable-diffusion-v35-large")
            .WithTitle("Stable Diffusion 3.5 Large")
            .WithDescription("Stability AI's SD 3.5 Large model with 8B parameters")
            .WithAuthor("Stability AI")
            .WithDimensions(1024, 1024)
            .WithDate("2024")
            .WithUsageHint("High-quality general purpose image generation")
            .WithTags("stable-diffusion", "text-to-image", "sd35")
            .WithFeatureFlag("fal_t2i_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("StabilityAI/sd-v35-medium")
            .WithEndpointOverride("fal-ai/stable-diffusion-v35-medium")
            .WithTitle("Stable Diffusion 3.5 Medium")
            .WithDescription("Balanced SD 3.5 model with 2.5B parameters")
            .WithAuthor("Stability AI")
            .WithDimensions(1024, 1024)
            .WithDate("2024")
            .WithUsageHint("Good balance of quality and speed")
            .WithTags("stable-diffusion", "text-to-image", "sd35")
            .WithFeatureFlag("fal_t2i_params")
            .Build(),

        // ==================== xAI (Grok) ====================
        ModelDefinitionBuilder.Create()
            .WithId("Grok/grok-imagine-image")
            .WithEndpointOverride("xai/grok-imagine-image")
            .WithTitle("Grok Imagine Image")
            .WithDescription("Generate highly aesthetic images with xAI's Grok Imagine model")
            .WithAuthor("xAI")
            .WithDimensions(1024, 1024)
            .WithDate("2024")
            .WithUsageHint("High aesthetic quality image generation")
            .WithTags("grok", "xai", "text-to-image", "aesthetic")
            .WithFeatureFlag("fal_t2i_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Grok/grok-imagine-video-t2v")
            .WithEndpointOverride("xai/grok-imagine-video/text-to-video")
            .WithTitle("Grok Imagine Video (T2V)")
            .WithDescription("Generate videos with audio from text using xAI's Grok Imagine")
            .WithAuthor("xAI")
            .WithDimensions(1280, 720)
            .WithDate("2025")
            .WithUsageHint("Text-to-video with audio generation")
            .WithTags("grok", "xai", "text-to-video", "video", "audio")
            .WithFeatureFlag("fal_video_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Grok/grok-imagine-video-i2v")
            .WithEndpointOverride("xai/grok-imagine-video/image-to-video")
            .WithTitle("Grok Imagine Video (I2V)")
            .WithDescription("Generate videos with audio from images using xAI's Grok Imagine")
            .WithAuthor("xAI")
            .WithDimensions(1280, 720)
            .WithDate("2025")
            .WithUsageHint("Image-to-video with audio generation")
            .WithTags("grok", "xai", "image-to-video", "video", "audio")
            .WithFeatureFlag("fal_video_params")
            .Build(),

        // ==================== Google ====================
        ModelDefinitionBuilder.Create()
            .WithId("Google/nano-banana-pro")
            .WithEndpointOverride("fal-ai/nano-banana-pro")
            .WithTitle("Nano Banana Pro")
            .WithDescription("Google's state-of-the-art image generation and editing model")
            .WithAuthor("Google")
            .WithDimensions(1024, 1024)
            .WithDate("2025")
            .WithUsageHint("High-quality image generation from Google")
            .WithTags("google", "text-to-image", "high-quality")
            .WithFeatureFlag("fal_t2i_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Google/veo-3.1-t2v")
            .WithEndpointOverride("fal-ai/veo3.1")
            .WithTitle("Veo 3.1 (T2V)")
            .WithDescription("Google DeepMind's most advanced AI video generation model with sound")
            .WithAuthor("Google DeepMind")
            .WithDimensions(1920, 1080)
            .WithDate("2025")
            .WithUsageHint("Highest quality text-to-video with audio")
            .WithTags("google", "veo", "text-to-video", "video", "audio")
            .WithFeatureFlag("fal_video_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Google/veo-3.1-fast-t2v")
            .WithEndpointOverride("fal-ai/veo3.1/fast")
            .WithTitle("Veo 3.1 Fast (T2V)")
            .WithDescription("Faster and more cost-effective version of Google's Veo 3.1")
            .WithAuthor("Google DeepMind")
            .WithDimensions(1920, 1080)
            .WithDate("2025")
            .WithUsageHint("Fast text-to-video with audio")
            .WithTags("google", "veo", "text-to-video", "video", "fast")
            .WithFeatureFlag("fal_video_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Google/veo-3.1-i2v")
            .WithEndpointOverride("fal-ai/veo3.1/image-to-video")
            .WithTitle("Veo 3.1 (I2V)")
            .WithDescription("Google Veo 3.1 image-to-video generation with audio")
            .WithAuthor("Google DeepMind")
            .WithDimensions(1920, 1080)
            .WithDate("2025")
            .WithUsageHint("Image-to-video with audio")
            .WithTags("google", "veo", "image-to-video", "video", "audio")
            .WithFeatureFlag("fal_video_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Google/veo-3.1-fast-i2v")
            .WithEndpointOverride("fal-ai/veo3.1/fast/image-to-video")
            .WithTitle("Veo 3.1 Fast (I2V)")
            .WithDescription("Fast Veo 3.1 image-to-video generation")
            .WithAuthor("Google DeepMind")
            .WithDimensions(1920, 1080)
            .WithDate("2025")
            .WithUsageHint("Fast image-to-video generation")
            .WithTags("google", "veo", "image-to-video", "video", "fast")
            .WithFeatureFlag("fal_video_params")
            .Build(),

        // ==================== Kling ====================
        ModelDefinitionBuilder.Create()
            .WithId("Kling/kling-image-v3")
            .WithEndpointOverride("fal-ai/kling-image/v3/text-to-image")
            .WithTitle("Kling Image V3")
            .WithDescription("Kling's V3 text-to-image generation model")
            .WithAuthor("Kling")
            .WithDimensions(1024, 1024)
            .WithDate("2025")
            .WithUsageHint("High-quality image generation")
            .WithTags("kling", "text-to-image")
            .WithFeatureFlag("fal_t2i_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Kling/kling-image-o3")
            .WithEndpointOverride("fal-ai/kling-image/o3/text-to-image")
            .WithTitle("Kling Omni 3")
            .WithDescription("Kling Omni 3 text-to-image generation model")
            .WithAuthor("Kling")
            .WithDimensions(1024, 1024)
            .WithDate("2025")
            .WithUsageHint("Latest Kling image generation")
            .WithTags("kling", "text-to-image", "omni")
            .WithFeatureFlag("fal_t2i_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Kling/kling-o3-pro-t2v")
            .WithEndpointOverride("fal-ai/kling-video/o3/pro/text-to-video")
            .WithTitle("Kling O3 Pro (T2V)")
            .WithDescription("Generate realistic videos using Kling O3 Pro")
            .WithAuthor("Kling")
            .WithDimensions(1920, 1080)
            .WithDate("2025")
            .WithUsageHint("Professional text-to-video generation")
            .WithTags("kling", "text-to-video", "video", "o3", "pro")
            .WithFeatureFlag("fal_video_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Kling/kling-o3-pro-i2v")
            .WithEndpointOverride("fal-ai/kling-video/o3/pro/image-to-video")
            .WithTitle("Kling O3 Pro (I2V)")
            .WithDescription("Generate realistic videos from images using Kling O3 Pro")
            .WithAuthor("Kling")
            .WithDimensions(1920, 1080)
            .WithDate("2025")
            .WithUsageHint("Professional image-to-video generation")
            .WithTags("kling", "image-to-video", "video", "o3", "pro")
            .WithFeatureFlag("fal_video_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Kling/kling-o3-std-t2v")
            .WithEndpointOverride("fal-ai/kling-video/o3/standard/text-to-video")
            .WithTitle("Kling O3 Standard (T2V)")
            .WithDescription("Generate videos using Kling O3 Standard")
            .WithAuthor("Kling")
            .WithDimensions(1920, 1080)
            .WithDate("2025")
            .WithUsageHint("Cost-effective text-to-video")
            .WithTags("kling", "text-to-video", "video", "o3", "standard")
            .WithFeatureFlag("fal_video_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Kling/kling-o3-std-i2v")
            .WithEndpointOverride("fal-ai/kling-video/o3/standard/image-to-video")
            .WithTitle("Kling O3 Standard (I2V)")
            .WithDescription("Generate videos from images using Kling O3 Standard")
            .WithAuthor("Kling")
            .WithDimensions(1920, 1080)
            .WithDate("2025")
            .WithUsageHint("Cost-effective image-to-video")
            .WithTags("kling", "image-to-video", "video", "o3", "standard")
            .WithFeatureFlag("fal_video_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Kling/kling-v3-pro-t2v")
            .WithEndpointOverride("fal-ai/kling-video/v3/pro/text-to-video")
            .WithTitle("Kling V3 Pro (T2V)")
            .WithDescription("Top-tier text-to-video with cinematic visuals and fluid motion")
            .WithAuthor("Kling")
            .WithDimensions(1920, 1080)
            .WithDate("2025")
            .WithUsageHint("Cinematic text-to-video generation")
            .WithTags("kling", "text-to-video", "video", "v3", "pro")
            .WithFeatureFlag("fal_video_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Kling/kling-v3-pro-i2v")
            .WithEndpointOverride("fal-ai/kling-video/v3/pro/image-to-video")
            .WithTitle("Kling V3 Pro (I2V)")
            .WithDescription("Top-tier image-to-video with cinematic visuals and fluid motion")
            .WithAuthor("Kling")
            .WithDimensions(1920, 1080)
            .WithDate("2025")
            .WithUsageHint("Cinematic image-to-video generation")
            .WithTags("kling", "image-to-video", "video", "v3", "pro")
            .WithFeatureFlag("fal_video_params")
            .Build(),

        // ==================== Qwen ====================
        ModelDefinitionBuilder.Create()
            .WithId("Qwen/qwen-image")
            .WithEndpointOverride("fal-ai/qwen-image")
            .WithTitle("Qwen Image")
            .WithDescription("Image generation foundation model with complex text rendering and precise editing")
            .WithAuthor("Alibaba")
            .WithDimensions(1024, 1024)
            .WithDate("2025")
            .WithUsageHint("Strong text rendering and image editing")
            .WithTags("qwen", "text-to-image", "text-rendering")
            .WithFeatureFlag("fal_t2i_params")
            .Build(),

        // ==================== Bria ====================
        ModelDefinitionBuilder.Create()
            .WithId("Bria/bria-fibo")
            .WithEndpointOverride("bria/fibo/generate")
            .WithTitle("Bria FIBO Generate")
            .WithDescription("Enterprise-grade image generation trained on licensed data")
            .WithAuthor("Bria")
            .WithDimensions(1024, 1024)
            .WithDate("2025")
            .WithUsageHint("Commercially safe image generation")
            .WithTags("bria", "text-to-image", "enterprise", "licensed")
            .WithFeatureFlag("fal_t2i_params")
            .Build(),

        // ==================== ByteDance ====================
        ModelDefinitionBuilder.Create()
            .WithId("ByteDance/seedream-v4")
            .WithEndpointOverride("fal-ai/bytedance/seedream/v4/edit")
            .WithTitle("Seedream 4.0")
            .WithDescription("ByteDance's image generation and editing model with unified architecture")
            .WithAuthor("ByteDance")
            .WithDimensions(1024, 1024)
            .WithDate("2025")
            .WithUsageHint("Unified generation and editing")
            .WithTags("bytedance", "seedream", "text-to-image", "image-editing")
            .WithFeatureFlag("fal_t2i_params")
            .Build(),

        // ==================== Reve ====================
        ModelDefinitionBuilder.Create()
            .WithId("Reve/reve-edit")
            .WithEndpointOverride("fal-ai/reve/edit")
            .WithTitle("Reve Edit")
            .WithDescription("High-quality image editing model")
            .WithAuthor("Reve")
            .WithDimensions(1024, 1024)
            .WithDate("2025")
            .WithUsageHint("Precise image editing")
            .WithTags("reve", "image-editing")
            .WithFeatureFlag("fal_t2i_params")
            .Build(),

        // ==================== ImagineArt ====================
        ModelDefinitionBuilder.Create()
            .WithId("ImagineArt/imagineart-1.5")
            .WithEndpointOverride("imagineart/imagineart-1.5-preview/text-to-image")
            .WithTitle("ImagineArt 1.5")
            .WithDescription("ImagineArt's text-to-image generation model")
            .WithAuthor("ImagineArt")
            .WithDimensions(1024, 1024)
            .WithDate("2025")
            .WithUsageHint("High-quality artistic image generation")
            .WithTags("imagineart", "text-to-image")
            .WithFeatureFlag("fal_t2i_params")
            .Build(),

        // ==================== OpenAI (Sora) ====================
        ModelDefinitionBuilder.Create()
            .WithId("Sora/sora-2-t2v")
            .WithEndpointOverride("fal-ai/sora-2/text-to-video")
            .WithTitle("Sora 2 (T2V)")
            .WithDescription("OpenAI's state-of-the-art video model for richly detailed dynamic clips with audio")
            .WithAuthor("OpenAI")
            .WithDimensions(1920, 1080)
            .WithDate("2025")
            .WithUsageHint("Highest quality text-to-video from OpenAI")
            .WithTags("sora", "openai", "text-to-video", "video", "audio")
            .WithFeatureFlag("fal_video_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Sora/sora-2-pro-t2v")
            .WithEndpointOverride("fal-ai/sora-2/text-to-video/pro")
            .WithTitle("Sora 2 Pro (T2V)")
            .WithDescription("Professional tier of OpenAI's Sora 2 video generation")
            .WithAuthor("OpenAI")
            .WithDimensions(1920, 1080)
            .WithDate("2025")
            .WithUsageHint("Premium text-to-video quality")
            .WithTags("sora", "openai", "text-to-video", "video", "pro")
            .WithFeatureFlag("fal_video_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Sora/sora-2-i2v")
            .WithEndpointOverride("fal-ai/sora-2/image-to-video")
            .WithTitle("Sora 2 (I2V)")
            .WithDescription("Create richly detailed dynamic clips with audio from images")
            .WithAuthor("OpenAI")
            .WithDimensions(1920, 1080)
            .WithDate("2025")
            .WithUsageHint("Image-to-video with audio from OpenAI")
            .WithTags("sora", "openai", "image-to-video", "video", "audio")
            .WithFeatureFlag("fal_video_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Sora/sora-2-pro-i2v")
            .WithEndpointOverride("fal-ai/sora-2/image-to-video/pro")
            .WithTitle("Sora 2 Pro (I2V)")
            .WithDescription("Professional tier image-to-video from OpenAI's Sora 2")
            .WithAuthor("OpenAI")
            .WithDimensions(1920, 1080)
            .WithDate("2025")
            .WithUsageHint("Premium image-to-video quality")
            .WithTags("sora", "openai", "image-to-video", "video", "pro")
            .WithFeatureFlag("fal_video_params")
            .Build(),

        // ==================== MiniMax ====================
        ModelDefinitionBuilder.Create()
            .WithId("MiniMax/hailuo-02-t2v")
            .WithEndpointOverride("fal-ai/minimax/hailuo-02/standard/text-to-video")
            .WithTitle("Hailuo-02 (T2V)")
            .WithDescription("MiniMax's Hailuo-02 text-to-video generation model")
            .WithAuthor("MiniMax")
            .WithDimensions(1280, 720)
            .WithDate("2025")
            .WithUsageHint("Text-to-video generation")
            .WithTags("minimax", "hailuo", "text-to-video", "video")
            .WithFeatureFlag("fal_video_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("MiniMax/hailuo-02-i2v")
            .WithEndpointOverride("fal-ai/minimax/hailuo-02/standard/image-to-video")
            .WithTitle("Hailuo-02 (I2V)")
            .WithDescription("MiniMax's advanced image-to-video generation model")
            .WithAuthor("MiniMax")
            .WithDimensions(1280, 720)
            .WithDate("2025")
            .WithUsageHint("Image-to-video generation")
            .WithTags("minimax", "hailuo", "image-to-video", "video")
            .WithFeatureFlag("fal_video_params")
            .Build(),

        // ==================== PixVerse ====================
        ModelDefinitionBuilder.Create()
            .WithId("PixVerse/pixverse-v5-t2v")
            .WithEndpointOverride("fal-ai/pixverse/v5/text-to-video")
            .WithTitle("PixVerse V5 (T2V)")
            .WithDescription("PixVerse V5 text-to-video generation")
            .WithAuthor("PixVerse")
            .WithDimensions(1280, 720)
            .WithDate("2025")
            .WithUsageHint("Text-to-video generation")
            .WithTags("pixverse", "text-to-video", "video")
            .WithFeatureFlag("fal_video_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("PixVerse/pixverse-v5-i2v")
            .WithEndpointOverride("fal-ai/pixverse/v5/image-to-video")
            .WithTitle("PixVerse V5 (I2V)")
            .WithDescription("PixVerse V5 image-to-video generation")
            .WithAuthor("PixVerse")
            .WithDimensions(1280, 720)
            .WithDate("2025")
            .WithUsageHint("Image-to-video generation")
            .WithTags("pixverse", "image-to-video", "video")
            .WithFeatureFlag("fal_video_params")
            .Build(),

        // ==================== Wan ====================
        ModelDefinitionBuilder.Create()
            .WithId("Wan/wan-2.2-t2v")
            .WithEndpointOverride("fal-ai/wan/v2.2-a14b/text-to-video")
            .WithTitle("Wan 2.2 (T2V)")
            .WithDescription("High-quality video generation with motion diversity from text prompts")
            .WithAuthor("Wan")
            .WithDimensions(1280, 720)
            .WithDate("2025")
            .WithUsageHint("Text-to-video with LoRA support")
            .WithTags("wan", "text-to-video", "video")
            .WithFeatureFlag("fal_video_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Wan/wan-2.2-i2v")
            .WithEndpointOverride("fal-ai/wan/v2.2-a14b/image-to-video")
            .WithTitle("Wan 2.2 (I2V)")
            .WithDescription("High-quality video generation from images with LoRA support")
            .WithAuthor("Wan")
            .WithDimensions(1280, 720)
            .WithDate("2025")
            .WithUsageHint("Image-to-video with LoRA support")
            .WithTags("wan", "image-to-video", "video")
            .WithFeatureFlag("fal_video_params")
            .Build(),

        // ==================== Lightricks (LTX) ====================
        ModelDefinitionBuilder.Create()
            .WithId("LTX/ltx-2-19b-i2v")
            .WithEndpointOverride("fal-ai/ltx-2-19b/image-to-video")
            .WithTitle("LTX-2 19B (I2V)")
            .WithDescription("Generate video with audio from images using LTX-2")
            .WithAuthor("Lightricks")
            .WithDimensions(1280, 720)
            .WithDate("2025")
            .WithUsageHint("Image-to-video with audio")
            .WithTags("ltx", "image-to-video", "video", "audio")
            .WithFeatureFlag("fal_video_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("LTX/ltx-13b-distilled-i2v")
            .WithEndpointOverride("fal-ai/ltx-video-13b-distilled/image-to-video")
            .WithTitle("LTX 13B Distilled (I2V)")
            .WithDescription("Generate videos from prompts and images using custom LoRA")
            .WithAuthor("Lightricks")
            .WithDimensions(1280, 720)
            .WithDate("2025")
            .WithUsageHint("Fast image-to-video with LoRA support")
            .WithTags("ltx", "image-to-video", "video", "lora")
            .WithFeatureFlag("fal_video_params")
            .Build(),

        // ==================== Vidu ====================
        ModelDefinitionBuilder.Create()
            .WithId("Vidu/vidu-q3-t2v")
            .WithEndpointOverride("fal-ai/vidu/q3/text-to-video")
            .WithTitle("Vidu Q3 (T2V)")
            .WithDescription("Vidu's latest Q3 pro text-to-video model")
            .WithAuthor("Vidu")
            .WithDimensions(1280, 720)
            .WithDate("2025")
            .WithUsageHint("Text-to-video generation")
            .WithTags("vidu", "text-to-video", "video")
            .WithFeatureFlag("fal_video_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Vidu/vidu-q3-i2v")
            .WithEndpointOverride("fal-ai/vidu/q3/image-to-video")
            .WithTitle("Vidu Q3 (I2V)")
            .WithDescription("Vidu's latest Q3 pro image-to-video model")
            .WithAuthor("Vidu")
            .WithDimensions(1280, 720)
            .WithDate("2025")
            .WithUsageHint("Image-to-video generation")
            .WithTags("vidu", "image-to-video", "video")
            .WithFeatureFlag("fal_video_params")
            .Build(),

        // ==================== Decart ====================
        ModelDefinitionBuilder.Create()
            .WithId("Decart/lucy-14b-i2v")
            .WithEndpointOverride("decart/lucy-14b/image-to-video")
            .WithTitle("Lucy-14B (I2V)")
            .WithDescription("Lightning fast image-to-video generation")
            .WithAuthor("Decart")
            .WithDimensions(1280, 720)
            .WithDate("2025")
            .WithUsageHint("Ultra-fast image-to-video")
            .WithTags("decart", "lucy", "image-to-video", "video", "fast")
            .WithFeatureFlag("fal_video_params")
            .Build(),

        // ==================== Utility ====================
        ModelDefinitionBuilder.Create()
            .WithId("Utility/rembg")
            .WithEndpointOverride("fal-ai/imageutils/rembg")
            .WithTitle("Remove Background")
            .WithDescription("Remove backgrounds from images automatically")
            .WithAuthor("Fal.ai")
            .WithDimensions(1024, 1024)
            .WithDate("2024")
            .WithUsageHint("Quick background removal for any image")
            .WithTags("utility", "background-removal")
            .WithFeatureFlag("fal_utility_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Utility/clarity-upscaler")
            .WithEndpointOverride("fal-ai/clarity-upscaler")
            .WithTitle("Clarity Upscaler")
            .WithDescription("AI-powered image upscaling with detail enhancement")
            .WithAuthor("Fal.ai")
            .WithDimensions(4096, 4096)
            .WithDate("2024")
            .WithUsageHint("Upscale images up to 4x with enhanced details")
            .WithTags("utility", "upscaler", "enhancement")
            .WithFeatureFlag("fal_utility_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Utility/topaz-upscale")
            .WithEndpointOverride("fal-ai/topaz/upscale/image")
            .WithTitle("Topaz Upscale")
            .WithDescription("Topaz-powered image upscaling")
            .WithAuthor("Topaz")
            .WithDimensions(4096, 4096)
            .WithDate("2025")
            .WithUsageHint("Professional image upscaling")
            .WithTags("utility", "upscaler", "topaz")
            .WithFeatureFlag("fal_utility_params")
            .Build(),
        ModelDefinitionBuilder.Create()
            .WithId("Utility/bria-rmbg")
            .WithEndpointOverride("fal-ai/bria/background/remove")
            .WithTitle("Bria RMBG 2.0")
            .WithDescription("Bria's background removal model")
            .WithAuthor("Bria")
            .WithDimensions(1024, 1024)
            .WithDate("2025")
            .WithUsageHint("High-quality background removal")
            .WithTags("utility", "background-removal", "bria")
            .WithFeatureFlag("fal_utility_params")
            .Build()
    ];

    #endregion
}
